(("doom" . ((user-emacs-directory . "~/.emacs-distros/doom-emacs")
	    ((env . (("DOOMDIR" . "~/.dotfiles/.doom.d"))))
	    (server-name . "doom")))
 ("spacemacs" . ((user-emacs-directory . "~/.emacs-distros/spacemacs")
		 (env . (("SPACEMACSDIR" . "~/.dotfiles/.spacemacs.d")))))
 ("custom" . ((user-emacs-directory . "~/.dotfiles/.emacs.d")
	      (server-name . "gnu"))))
