require("nsalesky.settings")
require("nsalesky.lazy")
require("nsalesky.remap")
require("nsalesky.utils")
require("nsalesky.functions")
require("nsalesky.auto_commands")
require("nsalesky.settings_override")
