#+title: My Emacs Configuration
#+author: Nick Salesky
#+PROPERTY: header-args:emacs-lisp :tangle ./init.el
#+STARTUP: overview

* Contents :TOC:
:PROPERTIES:
:TOC:      :include all
:END:

- [[#about][About]]
- [[#installation][Installation]]
- [[#emacs-initialization][Emacs Initialization]]
  - [[#set-some-early-ui-settings][Set some early UI settings]]
- [[#package-system-setup][Package System Setup]]
- [[#personal-information][Personal Information]]
- [[#configure-emacs-builtin-packages][Configure Emacs builtin packages]]
  - [[#saveplace-remember-your-location-in-a-file][Saveplace: Remember your location in a file]]
  - [[#savehist-keep-track-of-minibuffer-history][Savehist: Keep track of minibuffer history]]
  - [[#time][Time]]
- [[#generalel][General.el]]
- [[#ui][UI]]
  - [[#basic-emacs-appearance-settings][Basic Emacs appearance settings]]
  - [[#fonts][Fonts]]
  - [[#theme][Theme]]
  - [[#modeline][Modeline]]
  - [[#dashboard][Dashboard]]
  - [[#smooth-scrolling][Smooth Scrolling]]
  - [[#helpful][Helpful]]
  - [[#hl-todo-highlight-and-navigate-todo-keywords][Hl-todo: Highlight and navigate TODO keywords]]
  - [[#hl-line-highlight-the-current-line][Hl-line: Highlight the current line]]
  - [[#transparent-frame][Transparent Frame]]
- [[#vertico-minibuffer][Vertico: Minibuffer]]
  - [[#consult-add-helpful-functions-with-completion][Consult: add helpful functions with completion]]
  - [[#orderless-match-the-different-parts-of-completion-candidates][Orderless: match the different parts of completion candidates]]
  - [[#all-the-icons-completion-add-icons-to-completion-candidates][All-the-icons-completion: add icons to completion candidates]]
  - [[#embark][Embark]]
- [[#editor][Editor]]
  - [[#aggressive-indent-always-keep-code-properly-indented][Aggressive-indent: Always keep code properly indented]]
  - [[#rainbow-delimiters-different-color-for-each-parenthesis-level][Rainbow-delimiters: Different color for each parenthesis level]]
  - [[#smartparens-match-grouping-characters][SmartParens: Match grouping characters]]
  - [[#yasnippet-create-common-snippets][YASnippet: Create common snippets]]
  - [[#company-auto-completion][Company: Auto completion]]
  - [[#corfu-completion-at-point][Corfu: Completion at point]]
  - [[#which-key-list-commands-for-current-prefix][Which-key: List commands for current prefix]]
  - [[#olivetti-centered-document-editing][Olivetti: Centered document editing]]
  - [[#iedit-simple-multi-cursor-editing][Iedit: Simple multi-cursor editing]]
  - [[#comments][Comments]]
- [[#spell-checker][Spell checker]]
  - [[#flyspell][Flyspell]]
  - [[#flyspell-correct-show-list-of-correct-spelling-suggestions][Flyspell-correct: Show list of correct spelling suggestions]]
- [[#project-management][Project Management]]
  - [[#projectile][Projectile]]
  - [[#treemacs-a-tree-layout-file-explorer][Treemacs: A tree layout file explorer]]
  - [[#perspective-give-projects-their-own-named-workspaces][Perspective: Give projects their own named workspaces]]
  - [[#tab-bar-mode][Tab-bar-mode]]
- [[#keybindings-and-basic-feature-configuration][Keybindings and Basic Feature Configuration]]
  - [[#esc-quits-prompts][ESC quits prompts]]
  - [[#movement][Movement]]
  - [[#hydra][Hydra]]
  - [[#evil][Evil]]
  - [[#tabs-not-spaces][Tabs Not Spaces]]
  - [[#line-formatting][Line Formatting]]
  - [[#files][Files]]
  - [[#toggling][Toggling]]
  - [[#open-applications][Open Applications]]
  - [[#windows][Windows]]
  - [[#buffers][Buffers]]
  - [[#search][Search]]
  - [[#help][Help]]
  - [[#dired][Dired]]
- [[#version-control][Version Control]]
  - [[#magit][Magit]]
  - [[#forge-issue-github-pull-requests-and-more][Forge: issue GitHub pull requests and more]]
  - [[#blamer-git-blame-the-current-line][Blamer: Git blame the current line]]
- [[#org-mode][Org Mode]]
  - [[#basic-config][Basic config]]
  - [[#fonts-1][Fonts]]
  - [[#configure-babel][Configure Babel]]
  - [[#auto-tangle-configuration-files][Auto-tangle configuration files]]
  - [[#org-agenda-and-org-capture][Org-agenda and org-capture]]
  - [[#org-roam][Org-roam]]
  - [[#org-journal][Org-journal]]
  - [[#org-present][Org-present]]
  - [[#org-modern][Org-modern]]
  - [[#table-of-contents][Table of Contents]]
  - [[#imenu-list][Imenu-list]]
- [[#note-taking][Note Taking]]
  - [[#denote][Denote]]
- [[#shellsterminal-emulators][Shells/Terminal Emulators]]
  - [[#term-mode][term-mode]]
  - [[#eshell][Eshell]]
  - [[#vterm][Vterm]]
- [[#programming][Programming]]
  - [[#format-all-the-code-simple-code-formatting][Format All The Code: Simple code formatting]]
  - [[#flycheck][Flycheck]]
  - [[#lsp-language-server-protocols][LSP: Language-server protocols]]
  - [[#eglot-language-server-protocols][Eglot: Language-server protocols]]
  - [[#dap-debugging-support][DAP: Debugging support]]
  - [[#realgud][Realgud]]
  - [[#tree-sitter][Tree-Sitter]]
  - [[#wakatime][Wakatime]]
  - [[#cc][C/C++]]
  - [[#clojure][Clojure]]
  - [[#glsl-opengl-shaders][GLSL: OpenGL shaders]]
  - [[#go][Go]]
  - [[#java][Java]]
  - [[#python][Python]]
  - [[#typescript][Typescript]]
  - [[#retro-assembly][Retro Assembly]]
  - [[#rust][Rust]]
  - [[#web][Web]]
- [[#irc][IRC]]
- [[#documents][Documents]]
  - [[#pdfs][PDFs]]
  - [[#ebooks][Ebooks]]

* About
This is my personal Emacs config that I've built with the "help" :) of many other open-source configs, blog posts, articles, etc. When possible, I try to attribute specific sections to the original source for both my benefit and anyone else's. I started using Emacs with the help of [[https://github.com/doomemacs/doomemacs][Doom Emacs]], so many of my keybindings and other settings are inspired by that.

One important thing is that I haven't really done any effort to shorten the Emacs loading time, so this config takes a while to start up (about 8 seconds or so on my machine). I usually just keep Emacs open or use a daemon so this isn't an issue for me, but maybe something for me to look into in the future!

Some specific configs I looked at include:

- [[https://github.com/dakra/dmacs][Dmacs]] (the structure of this config file is heavily inspired by this!)
- [[https://www.youtube.com/watch?v=SCPoF1PTZpI&t=896s][System Crafters]]

* Installation

Installation should be fairly straightforward. The first time Emacs runs this config, it should hopefully install all the necessary packages automatically. If it doesn't prompt you, you'll need to run ~M-x all-the-icons-install-fonts~.

* Emacs Initialization
Add my custom ELisp files to the load-path.
#+BEGIN_SRC emacs-lisp

(add-to-list 'load-path "~/.dotfiles/.emacs.d/lisp")

#+END_SRC 

Disable certain byte compiler warnings to cut down on the noise for (usually unnecessary) errors.

#+BEGIN_SRC emacs-lisp
(setq byte-compile-warnings '(not free-vars unresolved noruntime lexical make-local)
      native-comp-async-report-warnings-errors nil)


#+END_SRC 

Increase the garbage collection threshold and process data chunking for performance.

#+BEGIN_SRC emacs-lisp

(setq gc-cons-threshold 100000000
      read-process-output-max (* 1024 1024))

#+END_SRC 

** Set some early UI settings

Disable the Toolbar and Menubar in the early-init.el file via ~default-frame-alist~. This is slightly faster than loading them first before turning them off.

#+BEGIN_SRC emacs-lisp :tangle early-init.el

(push '(tool-bar-lines . 0) default-frame-alist)
(push '(menu-bar-lines . 0) default-frame-alist)

#+END_SRC 

Disable the scroll-bar
#+BEGIN_SRC emacs-lisp
(scroll-bar-mode -1)
#+END_SRC 

Disable tooltips
#+BEGIN_SRC emacs-lisp
(tooltip-mode -1)
#+END_SRC 

Disable alarms
#+BEGIN_SRC emacs-lisp
(setq ring-bell-function 'ignore)
#+END_SRC 

Give some breathing room with the fringe
#+BEGIN_SRC emacs-lisp
(set-fringe-mode 10)
#+END_SRC 

Disable the startup message
#+BEGIN_SRC emacs-lisp
(setq inhibit-startup-message t)
#+END_SRC 

Use short answers for prompts
#+BEGIN_SRC emacs-lisp
(setq use-short-answers t)
#+END_SRC 

Don't confirm nonexistent files or buffers
#+BEGIN_SRC emacs-lisp
(setq confirm-nonexistent-file-or-buffer nil)
#+END_SRC 

* Package System Setup
For now, I just use the standard Emacs ~package.el~ system with ~use-package~.

*** Initialize package sources
Setup the package repos to search when installing new packages.

#+BEGIN_SRC emacs-lisp

;; (require 'package)

;; (setq package-archives '(("melpa" . "https://melpa.org/packages/")
;; 			 ;("melpa-stable" . "https://stable.melpa.org/packages/")
;; 			 ("elpa" . "https://elpa.gnu.org/packages/")
;;              ("nongnu" . "https://elpa.nongnu.org/nongnu/")))

;; (package-initialize)
;; (unless package-archive-contents
;;   (package-refresh-contents))

#+END_SRC 

*** Straight.el

#+BEGIN_SRC emacs-lisp

(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

#+END_SRC 

*** Use-Package
Set up ~use-package~ for installing further packages with ~straight.el~

#+BEGIN_SRC emacs-lisp

;; Initalize use-package on non-Linux platforms
;; (unless (package-installed-p 'use-package)
;;   (package-install 'use-package))

;; (require 'use-package)
;; (setq use-package-always-ensure t) ;; Always installs packages that you use if they're not already installed

;; ;; Make sure PATH is correct
;; (use-package exec-path-from-shell
;;   :config
;;   (exec-path-from-shell-initialize))

(straight-use-package 'use-package)
(setq straight-use-package-by-default t)

#+END_SRC 

* Personal Information
Set up the basic user information variables.

#+BEGIN_SRC emacs-lisp

(setq user-full-name "Nick Salesky"
      user-mail-address "nicksalesky@gmail.com")

#+END_SRC 

* Configure Emacs builtin packages
** Saveplace: Remember your location in a file
#+BEGIN_SRC emacs-lisp

(use-package saveplace
  :unless noninteractive
  :config
  (setq save-place-limit 1000)
  (save-place-mode))

#+END_SRC 

#+RESULTS:
: t

** Savehist: Keep track of minibuffer history
#+BEGIN_SRC emacs-lisp

(use-package savehist
  :unless noninteractive
  :defer 1
  :config
  (setq savehist-additional-variables '(compile-command kill-ring regexp-search-ring))
  (savehist-mode 1))

#+END_SRC 

#+RESULTS:

** Time
#+BEGIN_SRC emacs-lisp

;; (use-package time
;;   :defer t
;;   :config
;;   (setq display-time-24hr-format nil))

;; TODO look into displaying the current time in the modeline


#+END_SRC 

#+RESULTS:
: t

* General.el
Set up =general.el= to control all of my custom keybindings.

#+begin_src emacs-lisp

(use-package general
    :config
    (general-override-mode)
    ;; (general-evil-setup t)
    (general-create-definer my-leader
      :states '(normal visual emacs)
      :keymaps 'override
      :prefix "SPC"))

#+end_src

* UI
Set up all the fancy user-interface elements to make Emacs look nice.

** Basic Emacs appearance settings
Set the window title to display the current file and major mode.

#+BEGIN_SRC emacs-lisp
(setq-default frame-title-format '("%b [%m]"))
#+END_SRC 


Enable global visual line mode to wrap lines properly.

#+BEGIN_SRC emacs-lisp
(global-visual-line-mode 1)
#+END_SRC 

Enable line numbers globally for most modes, except the ones explicitly disabled.

#+BEGIN_SRC emacs-lisp

;; Enable line numbers
(column-number-mode)
(global-display-line-numbers-mode t)

;; Disable line numbers for some modes
(dolist (mode '(org-mode-hook
        term-mode-hook
        shell-mode-hook
        eshell-mode-hook
        treemacs-mode-hook
        pdf-view-mode-hook
        ))
(add-hook mode (lambda () (display-line-numbers-mode 0))))

#+END_SRC 

** Fonts
Set up the fonts for text rendering, pretty self explanatory :)

Here are my current font settings
#+BEGIN_SRC emacs-lisp

(set-face-attribute 'default nil :font "JetBrains Mono" :height 120)
(set-face-attribute 'fixed-pitch nil :font "JetBrains Mono" :height 120)
(set-face-attribute 'variable-pitch nil :font "Iosevka Aile" :height 140)

#+END_SRC 

Here are some of my older settings that I'm keeping around in case I ever want to switch back.
#+BEGIN_SRC emacs-lisp
;; (set-face-attribute 'default nil :font "JetBrains Mono" :height 120)
;; (set-face-attribute 'default nil :font "Rec Mono Semi Casual" :height 120)
;; (set-face-attribute 'fixed-pitch nil :font "Rec Mono Semi Casual" :height 120)
#+END_SRC 

Also install helpful icons useful for a ton of packages to add more visual detail. *NOTE* you'll have to run ~M-x all-the-icons-install-fonts~ in order to, well, install the fonts!

#+BEGIN_SRC emacs-lisp
(use-package all-the-icons)
#+END_SRC 

Emojis!!!! Works in any text mode :smile:

#+BEGIN_SRC emacs-lisp

(use-package emojify
  :config
  (global-emojify-mode))

#+END_SRC

** Theme
Give Emacs a nice color scheme! Other themes that I like include:
- doom-shades-of-purple
- doom-moonlight
- doom-flatwhite
- doom-tomorrow-day

#+BEGIN_SRC emacs-lisp

(use-package doom-themes
  :config
  (load-theme 'doom-shades-of-purple t))

(use-package mindre-theme
  :straight (:host github :repo "erikbackman/mindre-theme")
  :custom
  (mindre-use-more-bold t)
  (mindre-use-faded-lisp-parens t))
  ;; :config
  ;; (load-theme 'mindre t))

;; (use-package nano-theme
;;   :straight (nano-theme :type git :host github
;;                         :repo "rougier/nano-theme")
;;   :config
;;   (nano-light))

#+END_SRC 

**** Modus Themes

#+BEGIN_SRC emacs-lisp

(use-package modus-themes
  :init
  (setq modus-themes-italic-constructs t     ; use italics for comments
        modus-themes-bold-constructs t       ; use bold
        modus-themes-syntax '(faint)
        modus-themes-mixed-fonts t           ; Enable fixed and variable pitched fonts
        modus-themes-prompts '(italic)
        ;; modus-themes-mode-line '(accented borderless)
        modus-themes-mode-line '()
        modus-themes-subtle-line-numbers t
        ))
  ;; :config
  ;; (modus-themes-load-operandi))

#+END_SRC 

** Modeline
I use ~doom-modeline~ to manage my modeline.

#+BEGIN_SRC emacs-lisp

(use-package doom-modeline
  :init
  (setq doom-modeline-height 35
        doom-modeline-support-imenu t)
  (doom-modeline-mode 1))

(use-package nano-modeline
  :straight (nano-modeline :type git :host github
                           :repo "rougier/nano-modeline"))
  ;; :init
  ;; (nano-modeline-mode 1))

#+END_SRC 

** Dashboard
I like having a nice dashboard when Emacs loads in order to remember what I was last working on and (eventually!) view my ~org-agenda~ for the day. Maybe one day I'll revert to just a scratch buffer like others, but I'm sticking with this for now!

#+BEGIN_SRC emacs-lisp

;; Necessary for dashboard in order to get nice seperators between sections
(use-package page-break-lines)

(use-package dashboard
    :init
    (setq
        dashboard-image-banner-max-width 256
        dashboard-startup-banner "~/.dotfiles/.emacs.d/emacs.png"
        dashboard-center-content t
        dashboard-set-heading-icons t
        dashboard-set-file-icons t
        ;; dashboard-projects-switch-function 'projectile-switch-project
        dashboard-items '((recents . 5)
                          (projects . 5)
                          (agenda . 5)))
    :config
    (dashboard-setup-startup-hook))

#+END_SRC

** Smooth Scrolling
Make Emacs scroll more consistently with a small margin at the bottom.

#+BEGIN_SRC emacs-lisp
;; (use-package smooth-scrolling
;;   :init
;;   (setq smooth-scroll-margin 5)
;;   :config
;;   (smooth-scrolling-mode))

(pixel-scroll-mode)
(setq scroll-margin 5)

#+END_SRC 

** Helpful
Make the Emacs help pages more "helpful".

#+begin_src emacs-lisp

(use-package helpful
  :bind
  (("C-h f" . helpful-callable)
   ("C-h v" . helpful-variable)
   ("C-h k" . helpful-key)))


  
  ;; :custom
  ;; (counsel-describe-function-function #'helpful-callable)
  ;; (counsel-describe-variable-function #'helpful-variable)
  ;; :bind
  ;; ([remap describe-function] . counsel-describe-function)
  ;; ([remap describe-command] . helpful-command)
  ;; ([remap describe-variable] . counsel-describe-variable)
  ;; ([remap describe-key] . helpful-key))

#+end_src

** Hl-todo: Highlight and navigate TODO keywords

#+BEGIN_SRC emacs-lisp
(use-package hl-todo
  :config
  (global-hl-todo-mode))
#+END_SRC 

** Hl-line: Highlight the current line

Highlight the current line where point is present. I have this disabled for now because I was starting to find it difficult to differentiate the region from the current line.

#+BEGIN_SRC emacs-lisp
;; (add-hook 'prog-mode-hook 'hl-line-mode)
#+END_SRC 

** Transparent Frame
Creates a handy little function to toggle a semi-transparent window frame either for aeshetics or to view another window underneath Emacs.

#+BEGIN_SRC emacs-lisp

(defun ns/toggle-window-transparency ()
  "Toggle transparency."
  (interactive)
  (let ((alpha-transparency 75))
    (if (equal alpha-transparency (frame-parameter nil 'alpha-background))
        (set-frame-parameter nil 'alpha-background 100)
      (set-frame-parameter nil 'alpha-background alpha-transparency))))

#+END_SRC

* Vertico: Minibuffer
Sets up minibuffer completion with Vertico.

#+BEGIN_SRC emacs-lisp

(use-package vertico
  :init
  (vertico-mode))

#+END_SRC 

** Consult: add helpful functions with completion

#+BEGIN_SRC emacs-lisp

(use-package consult
  :bind
  ("C-s" . consult-line))

#+END_SRC 

** Orderless: match the different parts of completion candidates

#+BEGIN_SRC emacs-lisp

(use-package orderless
  :custom
  (completion-styles '(orderless basic))
  (completion-category-overrides '(
                                   (file (styles basic partial-completion))
                                   (eglot (styles orderless)))))

#+END_SRC 

** All-the-icons-completion: add icons to completion candidates

#+BEGIN_SRC emacs-lisp

(use-package all-the-icons-completion
  :config
  (all-the-icons-completion-mode))

#+END_SRC 

** Embark

#+BEGIN_SRC emacs-lisp

(use-package embark
  ;; TODO: set up bindings for embark-act and embark-dwim
  :bind
  (("C-." . embark-act)
   ("M-." . embark-dwim))

  :config

  ;; Hide the mode line for Embark buffers
  (add-to-list 'display-buffer-alist
               '("\\`\\*Embark Collect \\(Live\\|Completions\\)\\*"
                 nil
                 (window-parameters (mode-line-format . none)))))

(use-package embark-consult
  :after (embark consult)
  :demand t
  :hook
  (embark-collect-mode . consult-preview-at-point-mode))

#+END_SRC 

* Editor
** Aggressive-indent: Always keep code properly indented
#+BEGIN_SRC emacs-lisp

(use-package aggressive-indent
  :hook
  (emacs-lisp-mode-hook . aggressive-indent-mode))

#+END_SRC 

** Rainbow-delimiters: Different color for each parenthesis level

Give parenthases rainbow coloring depending on their nested level in all programming modes.

#+BEGIN_SRC emacs-lisp

(use-package rainbow-delimiters
    :hook (prog-mode . rainbow-delimiters-mode))

#+END_SRC 

** SmartParens: Match grouping characters

#+BEGIN_SRC emacs-lisp

(use-package smartparens
  :hook
  (prog-mode . smartparens-mode))

;; (use-package evil-smartparens
;;   :hook
;;   (smartparens-enabled . evil-smartparens-mode))
#+END_SRC

** YASnippet: Create common snippets
Add various templates to Emacs.

#+BEGIN_SRC emacs-lisp

(use-package yasnippet
  :config
  (yas-global-mode))

#+END_SRC

** Company: Auto completion
A good code-completion package. I might consider switching to Corfu at some point.

#+begin_src emacs-lisp

;; (use-package company
;;     :hook (prog-mode . company-mode)
;;     :bind (:map company-active-map
;;         ("<tab>" . company-complete-selection))
;;         ;; (:map lsp-mode-map
;;         ;; ("<tab>" . company-indent-or-complete-common))
;;     :custom
;;     (company-minimum-prefix-length 1)
;;     (company-idle-delay 0.0))

;; ;; Adds colors and icons to company-mode
;; (use-package company-box
;;     :hook (company-mode . company-box-mode))

#+end_src

** Corfu: Completion at point
Configure the ~corfu~ completion-at-point package. This configuration was inspired by the official documentation and [[https://kristofferbalintona.me/posts/202202270056/][here]].

#+BEGIN_SRC emacs-lisp

(use-package corfu
  :general
  (:keymaps 'corfu-map
            :states 'insert
            "C-n" #'corfu-next
            "C-p" #'corfu-previous
            "<escape>" #'corfu-quit
            "<return>" #'corfu-insert
            "M-d" #'corfu-show-documentation
            "M-l" #'corfu-show-location)
  
  :custom
  (corfu-auto t)
  (corfu-auto-prefix 0) ; Minimum length of prefix for auto-complete
  (corfu-auto-delay 0) ; Immediately start auto-completion

  (corfu-min-width 80) ; Min width of popup, I like to have it consistent
  (corfu-max-width corfu-min-width) ; Always have the same width
  (corfu-count 14) ; Max number of candidates to show
  (corfu-scroll-margin 4)
  ;; (corfu-cycle nil)

  ;; (corfu-quit-at-boundary nil)
  ;; (corfu-seperator ?\s)            ; Use space
  ;; (corfu-quit-no-match 'seperator) ; Don't quit if there is 'corfu-seperator' inserted
  ;; (corfu-quit-no-match t)
  (corfu-preview-current 'insert)  ; Preview first candidate
  (corfu-preselect-first t)        ; Preselect first candidate?

  (corfu-echo-documentation nil) ; Use 'corfu-doc' instead

  ;; Enable indentation+completion using the TAB key instead of M-TAB
  (tab-always-indent 'complete)
  ;; (completion-cycle-threshold nil)

  (corfu-excluded-modes '(eshell-mode))

  :init
  (global-corfu-mode))

  ;; :config
  ;; (general-add-advice '(corfu--setup corfu--teardown) :after 'evil-normalize-keymaps)
  ;; (evil-make-overriding-map corfu-map))


(use-package kind-icon
  :custom
  (kind-icon-default-face 'corfu-default)
  :config
  (add-to-list 'corfu-margin-formatters #'kind-icon-margin-formatter))

(use-package corfu-doc
  :hook (corfu-mode . corfu-doc-mode))

#+END_SRC 

** Which-key: List commands for current prefix

#+begin_src emacs-lisp

(use-package which-key
  ;; :after (ivy)
  :init (which-key-mode)
  :diminish which-key-mode
  :config
  (setq which-key-idle-delay 0.3))

#+end_src

** Olivetti: Centered document editing

#+BEGIN_SRC emacs-lisp

(use-package olivetti
  :custom
  (olivetti-body-width 110)
  (olivetti-style t))
  ;; :hook
  ;; (org-mode . olivetti-mode))

#+END_SRC

** Iedit: Simple multi-cursor editing
I took this from [[https://www.masteringemacs.org/article/iedit-interactive-multi-occurrence-editing-in-your-buffer]]

#+BEGIN_SRC emacs-lisp

(defun iedit-dwim (arg)
  "Starts iedit but uses \\[narrow-to-defun] to limit its scope."
  (interactive "P")
  (if arg
      (iedit-mode)
    (save-excursion
      (save-restriction
        (widen)
        (if iedit-mode
            (iedit-done)
          (narrow-to-defun)
          (iedit-start (current-word) (point-min) (point-max)))))))

(use-package iedit
  :bind
  ("C-;" . iedit-dwim))

#+END_SRC

** Comments

I'm not actually using any custom Elisp for comments right now, because ~comment-line~ bound to ~C-x C-;~ seems to work pretty well for me so far.
* Spell checker
** Flyspell
#+BEGIN_SRC emacs-lisp

;; (use-package flyspell
;;   :bind
;;   (:map flyspell-mode-map
;;         ("C-;" . nil)) ;; unbind this key so I can use it for iedit-dwim
  
;;   :hook ((prog-mode . flyspell-prog-mode)
;;         ((org-mode markdown-mode) . flyspell-mode)))

#+END_SRC 

** Flyspell-correct: Show list of correct spelling suggestions

#+BEGIN_SRC emacs-lisp

;; (use-package flyspell-correct
;;   :after (flyspell)
;;   :config
;;   (setq flyspell-correct-interface #'flyspell-correct-ivy))

#+END_SRC 

* Project Management
Tools to distinguish projects and quickly navigate inside projects and between them.

** Projectile
#+begin_src emacs-lisp

(use-package projectile
  :diminish projectile-mode
  :config (projectile-mode)
  ;; :custom ((projectile-completion-system 'ivy))
  :bind-keymap
  ("C-c p" . projectile-command-map)
  :init
  ;(when (file-directory-p "~/Documents")
    ;(setq projectile-project-search-path '("~/Documents")))
  (setq projectile-switch-project-action #'projectile-dired)

  :general
  (my-leader
      "SPC" '(projectile-find-file :which-key "Find file in project")
      "p" '(:ignore t :which-key "projects")
      "p p" '(projectile-switch-project :which-key "Switch project")))

;; (use-package counsel-projectile
;;   :config (counsel-projectile-mode))

#+end_src

** Treemacs: A tree layout file explorer
#+begin_src emacs-lisp

(use-package treemacs)
;; (use-package treemacs-evil
;;     :after (treemacs evil))
(use-package treemacs-projectile
    :after (treemacs projectile))
(use-package treemacs-icons-dired
    :hook (dired-mode . treemacs-icons-dired-enable-once))
(use-package treemacs-perspective
  :after (treemacs perspective))
(use-package treemacs-magit
    :after (treemacs magit))
;; (use-package lsp-treemacs
;;     :after (treemacs lsp-mode)
;;     :config (lsp-treemacs-sync-mode 1))
(use-package treemacs-all-the-icons
  :config
  (treemacs-load-theme "all-the-icons"))

#+end_src

** Perspective: Give projects their own named workspaces 
Add named workspaces to Emacs with their own buffers.

#+BEGIN_SRC emacs-lisp

(use-package perspective
    :init
    (setq persp-state-default-file "~/.dotfiles/.emacs.d/perspective-state"
          persp-mode-prefix-key (kbd "C-c M-p"))

    :config
    (persp-mode)

    ;; set up for Consult
    (consult-customize consult--source-buffer :hidden t :default nil)
    (add-to-list 'consult-buffer-sources persp-consult-source)

    :general
    (my-leader
      ;; "," '(persp-switch-buffer :which-key "Switch buffer")
      "b k" '(persp-remove-buffer :which-key "Remove buffer")

      "TAB" '(:ignore t :which-key "workspace")
      "TAB ." '(persp-switch :which-key "Switch to or create a workspace")
      "TAB r" '(persp-rename :which-key "Rename workspace")
      "TAB s" '(persp-state-save :which-key "Save workspaces")
      "TAB l" '(persp-state-load :which-key "Load saved workspaces")
      "TAB k" '(persp-kill :which-key "Kill workspace")
      "TAB 1" '((lambda () (interactive)(persp-switch-by-number 1)) :which-key "Switch to workspace 1")
      "TAB 2" '((lambda () (interactive)(persp-switch-by-number 2)) :which-key "Switch to workspace 2")
      "TAB 3" '((lambda () (interactive)(persp-switch-by-number 3)) :which-key "Switch to workspace 3")
      "TAB 4" '((lambda () (interactive)(persp-switch-by-number 4)) :which-key "Switch to workspace 4")
      "TAB 5" '((lambda () (interactive)(persp-switch-by-number 5)) :which-key "Switch to workspace 5")
      "TAB 6" '((lambda () (interactive)(persp-switch-by-number 6)) :which-key "Switch to workspace 6")
      "TAB 7" '((lambda () (interactive)(persp-switch-by-number 7)) :which-key "Switch to workspace 7")
      "TAB 8" '((lambda () (interactive)(persp-switch-by-number 8)) :which-key "Switch to workspace 8")
      "TAB 9" '((lambda () (interactive)(persp-switch-by-number 9)) :which-key "Switch to workspace 9")))

#+END_SRC

** Tab-bar-mode

#+BEGIN_SRC emacs-lisp



#+END_SRC 

* Keybindings and Basic Feature Configuration
Here's where I configure some basic Emacs features with keybindings.

** ESC quits prompts
Make ESC quit prompts.

#+begin_src emacs-lisp

(global-set-key (kbd "<escape>") 'keyboard-escape-quit)

#+end_src

#+RESULTS:
: keyboard-escape-quit

** Movement
Fundamental movement through text files

#+BEGIN_SRC emacs-lisp

;; Insert newlines when you C-n at the end of the buffer
;; (setq next-line-add-newlines t)

#+END_SRC 

** Hydra
*** Basic Config
Install the base Hydra package.

#+begin_src emacs-lisp
(use-package hydra)
#+end_src

*** Text Scale
Sets up a hydra to let me easily change the text scale.

#+begin_src emacs-lisp

(defhydra hydra-text-scale (:timeout 4)
  "scale text"
  ("j" text-scale-increase "up")
  ("k" text-scale-decrease "down")
  ("f" nil "finished" :exit t))

(my-leader
 "t k" '(hydra-text-scale/body :which-key "Scale text"))
#+end_src

** Evil
It's hard for me to function without VIM-style keybindings at this point, so Evil mode is a must-have feature.

#+begin_src emacs-lisp

(use-package undo-tree
  :config
  (global-undo-tree-mode))

;; (use-package evil
;;   :custom
;;   (evil-want-keybinding nil)
;;   (evil-want-integration t)
;;   (evil-want-integration t)
;;   (evil-want-C-u-scroll nil)
;;   (evil-want-C-i-jump nil)
;;   (evil-respect-visual-line-mode t)
;;   (evil-undo-system 'undo-tree)

;;   :config
;;   (evil-mode 1)
;;   (define-key evil-insert-state-map (kbd "C-g") 'evil-normal-state)
;;   (define-key evil-insert-state-map (kbd "C-h") 'evil-delete-backward-char-and-join)
;;   (define-key evil-insert-state-map (kbd "TAB") 'tab-to-tab-stop)

;;   ;; use visual line motions even outside of visual-line-mode buffers
;;   (evil-global-set-key 'motion "j" 'evil-next-visual-line)
;;   (evil-global-set-key 'motion "k" 'evil-previous-visual-line)

;;   ;; set the initial state for certain special modes
;;   (evil-set-initial-state 'messages-buffer-mode 'normal)
;;   (evil-set-initial-state 'dashboard-mode 'normal))
;;   ;; disable Evil-mode for certain buffers
;;   ;; (evil-set-initial-state 'eshell-mode 'emacs))

;; ;; Gives us default Evil configurations for a lot of other modes
;; (use-package evil-collection
;;   :after evil
;;   :config
;;   (evil-collection-init))

#+end_src

** Tabs Not Spaces
I took this basic configuration from [[https://dougie.io/emacs/indentation/]]

#+begin_src emacs-lisp

;; Set the default tab settings
(setq-default tab-width 4)
(setq-default indent-tabs-mode nil)
(setq-default c-basic-offset 4)
(setq-default python-indent-offset 4)
;; (setq-default evil-shift-width 4)

;; (setq-default electric-indent-inhibit t)

;; Make the backspace properly erase the whole tab instead of removing
;; 1 space at a time
(setq backward-delete-char-untabify-method 'hungry)

;; Make Evil mode backspace delete a whole tab's worth of spaces at a time
(general-define-key
    :states 'insert
    "<backspace>" 'backward-delete-char-untabify)

#+end_src

** Line Formatting
Keybindings for formatting lines of text/code.

#+BEGIN_SRC emacs-lisp

(my-leader
    ;; Line formatting
    "TAB TAB" '(smart-comment :which-key "Comment or uncomment lines"))

#+END_SRC

** Files
Keybindings for working with files.

#+BEGIN_SRC emacs-lisp

;; Keep track of recently-opened files
(recentf-mode 1)
(setq recentf-max-menu-items 25)
(setq recentf-max-saved-items 25)
(global-set-key (kbd "C-x C-r") 'consult-recent-file)


;; (my-leader
;;     "." '(find-file :which-key "Find file")

;;     "f" '(:ignore t :which-key "files")
;;     "f r" '(consult-recent-file :which-key "Open Recent Files")
;;     "f c" '((lambda () (interactive)(find-file "~/.dotfiles/.emacs.d/config.org")) :which-key "Open config.org"))

#+END_SRC

** Toggling
Some keybindings for toggling different functionalities on/off.

#+BEGIN_SRC emacs-lisp

(my-leader
     "t"  '(:ignore t :which-key "toggle")
     "t s" '(consult-theme :which-key "Choose theme")

     "t t" '(treemacs :which-key "Treemacs"))
     ;; "t y" '(lsp-treemacs-symbols :which-key "Treemacs Symbols"))

#+END_SRC

** Open Applications
Different keybindings to open certain applications.

#+BEGIN_SRC emacs-lisp

(my-leader
    "o" '(:ignore t :which-key "open"))

#+END_SRC

** Windows
Keybindings for operating windows.

#+BEGIN_SRC emacs-lisp

(define-key global-map (kbd "M-o") 'ace-window)

(my-leader
     "w" '(:ignore t :which-key "window")
     "wc" '(delete-window :which-key "Close window")
     "wv" '(split-window-right :which-key "Vertical split")
     "ws" '(split-window-below :which-key "Horizontal split")
     "wh" '(windmove-left :which-key "Select left window")
     "wj" '(windmove-down :which-key "Select down window")
     "wk" '(windmove-up :which-key "Select up window")
     "wl" '(windmove-right :which-key "Select right window"))

#+END_SRC

** Buffers
Some useful keybindings for working with buffers.

#+BEGIN_SRC emacs-lisp

(my-leader
      "," '(consult-buffer :which-key "Switch buffer")

      "b" '(:ignore t :which-key "buffers")
      "b k" '(kill-buffer :which-key "Kill buffer"))

#+END_SRC

Auto-revert all buffers by default
#+BEGIN_SRC emacs-lisp

(global-auto-revert-mode 1)

#+END_SRC 

** Search
Keybindings for searching within different contexts.

| COMMAND             | DESCRIPTION                                     | KEYBINDING |
|---------------------+-------------------------------------------------+------------|
| avy-goto-char-timer | Start typing some chars on screen, jump to them | s          |
| avy-pop-mark        | Jump back from last =avy= search                | S          |
| swiper              | Search the current buffer                       | SPC s b    |

#+BEGIN_SRC emacs-lisp

(general-define-key
 :states 'normal
 "s" 'avy-goto-char-timer
 "S" 'avy-pop-mark)

(general-define-key
 :states '(normal emacs)
 "C-s" 'consult-line)

(my-leader
  "s" '(:ignore t :which-key "search")
  "s b" '(consult-line :which-key "Search buffer"))

(use-package ag
  :general
  (my-leader
    "s p" '(projectile-ag :which-key "Search project")))
#+END_SRC

#+RESULTS:

** Help

#+BEGIN_SRC emacs-lisp

(my-leader
  "h" '(:ignore t :which-key "help")
  "h v" '(helpful-variable :which-key "Describe variable")
  "h f" '(helpful-callable :which-key "Describe function")
  "h k" '(helpful-key :which-key "Describe key"))

#+END_SRC 

** Dired
I use the base keybindings provided by [[https://github.com/emacs-evil/evil-collection/blob/master/modes/dired/evil-collection-dired.el][Evil Collection]] and also set up a few of my own.

#+BEGIN_SRC emacs-lisp

;; Simple keybinding to open dired if C-x d is too hard :)
(my-leader "d" '(dired :which-key "Dired"))

;; Set up some custom keybindings for Dired
(general-define-key
    :states 'normal
    :keymaps 'dired-mode-map
    "h" 'dired-up-directory
    "l" 'dired-find-file)

#+END_SRC 

* Version Control
** Magit

#+begin_src emacs-lisp

(use-package magit
  :general
  (my-leader
    "g" '(:ignore t :which-key "git")
    "g g" '(magit-status :which-key "Magit Status")))

#+end_src

** Forge: issue GitHub pull requests and more

#+BEGIN_SRC emacs-lisp
;(use-package forge)
#+END_SRC 

** Blamer: Git blame the current line

#+BEGIN_SRC emacs-lisp
(use-package blamer
  :general
  (my-leader
    "g b" '(global-blamer-mode :which-key "Toggle blamer mode")))
#+END_SRC 

* Org Mode
** Basic config
The very basics for Org-mode, setting up fonts and basic visual features.

#+begin_src emacs-lisp

 (defun ns/org-mode-setup ()
   (org-indent-mode)
   ;; (variable-pitch-mode 1)
   (visual-line-mode 1))

(defun ns/org-font-setup ()
  ;; Make sure that anything that should be fixed pitch in Org files actually appears that way
    (set-face-attribute 'org-block nil :foreground nil :inherit
                        'fixed-pitch)
    (set-face-attribute 'org-code nil :inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-table nil :inherit '(shadow fixed-pitch))
    ;; (set-face-attribute 'org-indent nil :inherit '(org-hide fixed-pitch))
    (set-face-attribute 'org-verbatim nil :inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-special-keyword nil :inherit
                    '(font-lock-comment-face fixed-pitch))
    (set-face-attribute 'org-meta-line nil :inherit
                        '(font-lock-comment-face fixed-pitch))
    (set-face-attribute 'org-checkbox nil :inherit 'fixed-pitch))

;; Got this from https://stackoverflow.com/questions/10969617/hiding-markup-elements-in-org-mode
(defun ns/org-toggle-emphasis ()
  "Toggle hiding/showing of org emphasis markers"
  (interactive)
  (if org-hide-emphasis-markers
      (set-variable 'org-hide-emphasis-markers nil)
    (set-variable 'org-hide-emphasis-markers t)))


;; (use-package org-contrib :pin nongnu)
(use-package org-contrib)

;; Org Mode
(use-package org
    :hook (org-mode . ns/org-mode-setup)
    :config
    ;; (ns/org-font-setup)
    (setq
     ;; org-hide-emphasis-markers nil
        org-ellipsis " ▾"
        org-pretty-entities t

        org-directory "~/notes"

        org-src-tab-acts-natively t
        org-src-preserve-indentation t

        org-todo-keywords
        '((sequence "TODO(t)" "NEXT(n)" "HOLD(h)" "|" "DONE(d!)")
            (sequence "BACKLOG(b)" "PLAN(p)" "READY(r)" "ACTIVE(a)" "REVIEW(v)"
                "WAIT(w@/!)" "HOLD(h)" "|" "COMPLETED(c)" "CANC(k@)")))

    :general
    (my-leader
      "n" '(:ignore t :which-key "notes")))

    ;; local-leader stuff
    ;; (my-local-leader
    ;;   :keymaps 'org-mode-map
    ;;   "b" '(org-babel-tangle :which-key "Org babel tangle")
    ;;   "t" '(


#+end_src

** Fonts
Set up ~variable-pitch~ fonts.

#+BEGIN_SRC emacs-lisp

(add-hook 'org-mode-hook 'variable-pitch-mode)

(require 'org-faces)

;; Resize Org headings
(dolist (face '((org-level-1 . 1.2)
                (org-level-2 . 1.1)
                (org-level-3 . 1.05)
                (org-level-4 . 1.0)
                (org-level-5 . 1.1)
                (org-level-6 . 1.1)
                (org-level-7 . 1.1)
                (org-level-8 . 1.1)))
  (set-face-attribute (car face) nil :font "Iosevka Aile" :weight 'medium :height (cdr face)))

;; Make the document title a bit bigger
(set-face-attribute 'org-document-title nil :font "Iosevka Aile" :weight 'bold :height 1.3)

;; Make sure certain org faces continue to use fixed-pitch face even whenn variable-pitch-mode is on
(set-face-attribute 'org-block nil :foreground nil :inherit 'fixed-pitch)
(set-face-attribute 'org-table nil :inherit 'fixed-pitch)
(set-face-attribute 'org-formula nil :inherit 'fixed-pitch)
(set-face-attribute 'org-code nil :inherit '(shadow fixed-pitch))
(set-face-attribute 'org-verbatim nil :inherit '(shadow fixed-pitch))
(set-face-attribute 'org-special-keyword nil :inherit '(font-lock-comment-face fixed-pitch))
(set-face-attribute 'org-meta-line nil :inherit '(font-lock-comment-facee fixed-pitch))
(set-face-attribute 'org-checkbox nil :inherit 'fixed-pitch)

#+END_SRC 

** Configure Babel
#+begin_src emacs-lisp

(org-babel-do-load-languages 'org-babel-load-languages
    '((emacs-lisp . t)
    (python . t)))

(setq org-confirm-babel-evaluate nil)


#+end_src

#+RESULTS:
: ((py . src python) (el . src emacs-lisp) (sh . src shell) (a . export ascii) (c . center) (C . comment) (e . example) (E . export) (h . export html) (l . export latex) (q . quote) (s . src) (v . verse))

** Auto-tangle configuration files
Automatically tangle the =config.org= file whenever it is saved. I currently have this turned off because I prefer to be safe and run =(org-babel-tangle)= manually whenever I'm done editing this file.

#+begin_src emacs-lisp

(defun ns/org-babel-tangle-config ()
  (when (string-equal (buffer-file-name)
                      (expand-file-name "~/.dotfiles/.emacs.d/config.org"))
    (let ((org-confirm-babel-evaluate nil))
      (org-babel-tangle))))

;(add-hook 'org-mode-hook (lambda () (add-hook 'after-save-hook #'ns/org-babel-tangle-config)))

#+end_src

** Org-agenda and org-capture
Here's where I set up my agenda system. I like to keep an inbox file where I can quickly capture new items without thinking about them and then organize them into my main agenda file later when I have time. My agenda system was directly inspired by [[https://www.labri.fr/perso/nrougier/GTD/index.html][nrougier]].

#+BEGIN_SRC emacs-lisp

(setq org-agenda-files (list "agenda/inbox.org"
                             "agenda/agenda.org"
                             "agenda/projects.org") ; add any files to be pulled from
      org-agenda-hide-tags-regexp "."     ; hide all tags in the agenda
      org-log-done 'time             ; log the time when a task is *DONE*
      org-agenda-compact-blocks nil
      org-agenda-block-separator nil
      )

#+END_SRC 

Now, I need to set up some capture templates to quickly add items to the agenda.

#+BEGIN_SRC emacs-lisp

(setq org-capture-templates
       `(("i" "Inbox" entry  (file "agenda/inbox.org")
        ,(concat "* TODO %?\n"
                 "/Entered on/ %U"))
         ("m" "Meeting entry" entry (file+headline "agenda.org" "Future")
          ,(concat "* %? :meeting:\n"
                   "<%<%Y-%m-%d %a %H:00>>"))
         ("n" "Note" entry (file "notes.org")
          ,(concat "* Note (%a)\n"
                   "/Entered on/ %U\n" "\n" "%?"))))
#+END_SRC 

Make it easier to move tasks from the inbox or other files over to ~projects.org~, and automatically save all agenda files after refiling.

#+BEGIN_SRC emacs-lisp

(setq org-refile-targets
      '(("agenda/projects.org" :regexp . "\\(?:\\(?:Note\\|Task\\)s\\)"))
      org-refile-use-outline-path 'file
      org-outline-path-complete-in-steps nil)

(defun ns/org-agenda-save-buffers ()
  "Save `org-agenda-files` buffers without user confirmation."
  (interactive)
  (message "Saving org-agenda-files buffers...")
  (save-some-buffers t
                     (lambda ()
                       (when (member (buffer-file-name) (org-agenda-files))
                         t)))
  (message "Saving org-agenda-files buffers... done"))

;; Automatically save after refile
(advice-add 'org-refile :after
            (lambda (&rest _)
              (ns/org-agenda-save-buffers)))


#+END_SRC 

Log when tasks are activated (first moved to *NEXT*) courtesy of [[https://emacs.stackexchange.com/questions/35751][Erik Anderson]]. 

#+BEGIN_SRC emacs-lisp

(defun log-todo-next-creation-date (&rest ignore)
  "Log NEXT creation time in the property drawer under the key 'ACTIVATED'"
  (when (and (string= (org-get-todo-state) "NEXT")
             (not (org-entry-get nil "ACTIVATED")))
    (org-entry-put nil "ACTIVATED" (format-time-string "[%Y-%m-%d]"))))
(add-hook 'org-after-todo-state-change-hook #'log-todo-next-creation-date)

#+END_SRC 

Set up a custom agenda command (*g*)

#+BEGIN_SRC emacs-lisp

(setq org-agenda-custom-commands
      '(("g" "Get Things Done (GTD)"
         ((agenda ""
                  ((org-agenda-span 1) ; limit display to a single day
                   (org-agenda-skip-function
                    '(org-agenda-skip-entry-if 'deadline))
                   (org-deadline-warning-days 0)))
          (todo "NEXT"
                ((org-agenda-skip-function
                  '(org-agenda-skip-entry-if 'deadline))
                 (org-agenda-prefix-format "  %i %-12:c [%e] ")
                 (org-agenda-overriding-header "\nTasks\n")))
          (agenda nil
                  ((org-agenda-entry-types '(:deadline))
                   (org-agenda-span 1)
                   (org-agenda-format-date "")
                   (org-deadline-warning-days 7)
                   (org-agenda-skip-function
                    '(org-agenda-skip-entry-if 'notregexp "\\* NEXT"))
                   (org-agenda-overriding-header "\nDeadlines")))
          (tags-todo "inbox"
                     ((org-agenda-prefix-format "  %?-12t% s")
                      (org-agenda-overriding-header "\nInbox\n")))
          (tags "CLOSED>=\"<today>\""
                ((org-agenda-overriding-header "\nCompleted today\n")))))))

#+END_SRC 

Finally, define a keybinding for =org-capture= and opening up the =org-agenda=

#+BEGIN_SRC emacs-lisp

(my-leader
  "c" '(org-capture :which-key "Capture")
  "a" '(org-agenda :which-key "Agenda"))

#+END_SRC 

** Org-roam

#+BEGIN_SRC emacs-lisp

;; (use-package org-roam
;;   :custom
;;   (org-roam-directory "~/notes/roam/")
;;   :config
;;   (setq org-roam-node-display-template (concat "${title:*} " (propertize "${tags:10}" 'face 'org-tag)))
;;   (org-roam-db-autosync-mode)
;;   :general
;;   (my-leader
;;     "n r" '(:ignore t :which-key "roam")
;;     ;;"n r" '(:keymap org-roam-mode-map :which-key "roam")
;;     "n r f" '(org-roam-node-find :which-key "Find Node")
;;     "n r i" '(org-roam-node-insert :which-key "Insert Node")
;;     "n r o" '(org-roam-node-open :which-key "Open Node")
;;     "n r g" '(org-roam-graph :which-key "Graph")))

#+END_SRC

#+RESULTS:

** Org-journal

#+BEGIN_SRC emacs-lisp

;; (use-package org-journal
;;   :general
;;   (my-leader
;;     "n j" '(:ignore t :which-key "journal")
;;     "n j j" '(org-journal-new-entry :which-key "New entry")
;;     "n j r" '(org-journal-read-entry :which-key "Read entry")
;;     "n j s" '(org-journal-search :which-key "Search journal"))
  
;;   :custom
;;   (org-journal-dir "~/notes/journal")
;;   (org-journal-file-format "%Y-%m-%d.org")
;;   (org-journal-date-format "%B %d, %Y (%A) ")
;;   (org-journal-date-prefix "* ")
;;   (org-journal-time-prefix "** "))

#+END_SRC 

** Org-present

#+BEGIN_SRC emacs-lisp

(defun ns/org-present-begin ()
  (setq-local ns/olivetti-mode-enabled (bound-and-true-p olivetti-mode)) ;; remember if olivetti was already enabled or not
  (olivetti-mode 1)                                                      ;; enable olivetti-mode regardless

  ;; Tweak the font sizes
  (setq-local face-remapping-alist '((default (:height 1.5) variable-pitch)
                                     (header-line (:height 4.0) variable-pitch)
                                     (org-document-title (:height 1.75) org-document-title)
                                     (org-code (:height 1.55) org-code)
                                     (org-verbatim (:height 1.55) org-verbatim)
                                     (org-block (:height 1.25) org-block)
                                     (org-block-begin-line (:height 0.7) org-block)))

  ;; Set a blank header line string to create some blank space at the top
  (setq-local header-line-format " ")

  (message "Starting presentation. Good luck!"))

(defun ns/org-present-end ()
  (unless (symbol-value 'ns/olivetti-mode-enabled)
    (olivetti-mode 0))                                                   ;; disable olivetti-mode only if it wasn't open before the presentation

  ;; Reset the font customizations
  (setq-local face-remapping-alist '((default variable-pitch default)))

  ;; Reset the header line back to nothing
  (setq-local header-line-format nil)

  (message "Ending presentation. Nice job!"))

(use-package org-present
  :config
  (add-hook 'org-present-mode-hook 'ns/org-present-begin)
  (add-hook 'org-present-mode-quit-hook 'ns/org-present-end))

#+END_SRC 

** Org-modern
Give Org-mode documents some extra visual polish.

#+BEGIN_SRC emacs-lisp

;; (use-package org-modern
;;     :config
;;     (add-hook 'org-mode-hook #'org-modern-mode)
;;     (add-hook 'org-agenda-finalize #'org-modern-agenda))

#+END_SRC

** Table of Contents

#+BEGIN_SRC emacs-lisp

(use-package toc-org
  :hook
  (org-mode . toc-org-mode))

#+END_SRC 

#+RESULTS:
| toc-org-mode | #[0 \301\211\207 [imenu-create-index-function org-imenu-get-tree] 2] | olivetti-mode | #[0 \300\301\302\303\304$\207 [add-hook change-major-mode-hook org-show-all append local] 5] | #[0 \300\301\302\303\304$\207 [add-hook change-major-mode-hook org-babel-show-result-all append local] 5] | org-babel-result-hide-spec | org-babel-hide-all-hashes | ns/org-mode-setup | (lambda nil (display-line-numbers-mode 0)) | org-eldoc-load |

** Imenu-list

#+BEGIN_SRC emacs-lisp

(use-package imenu-list
  :init
  (setq imenu-list-position 'left)
  :general
  (my-leader
   "t i" '(imenu-list-smart-toggle :which-key "Imenu")))
  

#+END_SRC 

* Note Taking
** Denote

#+BEGIN_SRC emacs-lisp

(use-package denote
  :straight (denote :type git :host gitlab
                    :repo "protesilaos/denote")
  :custom
  (denote-directory "~/notes")
  (denote-known-keywords
    '("emacs" "personal" "journal")))

#+END_SRC 

* Shells/Terminal Emulators
** term-mode

#+BEGIN_SRC emacs-lisp

(use-package term
  :custom
  (explicit-shell-file-name "fish"))

(use-package eterm-256color
  :hook
  (term-mode . eterm-256color-mode))

#+END_SRC

** Eshell
Sets up Eshell so it can be easily toggled in a small pop-up window.

#+BEGIN_SRC emacs-lisp

(use-package eshell-toggle
  :straight (eshell-toggle :type git :host github
                           :repo "4DA/eshell-toggle")
  :custom
  (eshell-toggle-size-fraction 3)         ; use 30% of the frame (?)
  (eshell-toggle-use-projectile-root t)   ; use projectile root if it exists
  (eshell-toggle-default-directory "~")   ; default to home directory
  :general
  (my-leader
    "o e" '(eshell-toggle :which-key "Open Eshell")))

#+END_SRC 

Customize the Eshell prompt (with a package!!!)

#+BEGIN_SRC emacs-lisp

(use-package eshell-git-prompt
  :straight (eshell-git-prompt :type git :host github
                               :repo "xuchunyang/eshell-git-prompt")
  :config
  (eshell-git-prompt-use-theme 'multiline2))

#+END_SRC 

** Vterm
#+BEGIN_SRC emacs-lisp

(use-package vterm
  :custom
  (vterm-shell "fish")
  (vterm-max-scrollback 10000))

#+END_SRC 

* Programming
** Format All The Code: Simple code formatting
A simple code formatting system for a ton of languages.

#+begin_src emacs-lisp

(use-package format-all)
  ;:hook
  ;(prog-mode . format-all-mode)

#+end_src

** Flycheck
#+BEGIN_SRC emacs-lisp

(use-package flycheck
  :config
  (global-flycheck-mode))

#+END_SRC 

** LSP: Language-server protocols
#+begin_src emacs-lisp

;; (use-package lsp-mode
;;     :commands (lsp lsp-deferred)
;;     :init
;;     (setq lsp-lens-enable t
;;           lsp-signature-auto-activate nil
;;           lsp-ui-doc-mode t)
;;     :general
;;     (evil-define-key 'normal lsp-mode-map (kbd "/") lsp-command-map)
;;     :config
;;     (lsp-enable-which-key-integration t)
;;     :custom

;;     ;; Enable/disable type hints as you type for Rust
;;     (lsp-rust-analyzer-server-display-inlay-hints t)
;;     (lsp-rust-analyzer-display-lifetime-elision-hints-enable "skip_trivial")
;;     (lsp-rust-analyzer-display-chaining-hints nil)
;;     (lsp-rust-analyzer-display-lifetime-elision-hints-use-parameter-names nil)
;;     (lsp-rust-analyzer-display-closure-return-type-hints t)
;;     (lsp-rust-analyzer-display-parameter-hints t)
;;     (lsp-rust-analyzer-display-reborrow-hints nil))

;; ;; (use-package lsp-ivy)

;; (use-package lsp-ui
;;     :hook (lsp-mode . lsp-ui-mode)
;;     :custom
;;     (lsp-ui-peek-always-show t)
;;     (lsp-ui-sideline-show-hover t)
;;     (lsp-ui-doc-position 'bottom)
;;     (lsp-ui-doc-enable nil))

#+end_src

** Eglot: Language-server protocols

#+BEGIN_SRC emacs-lisp

(use-package eglot
  :custom
  (eglot-events-buffer-size 0)) ;; Disable the events buffer for performance
  

#+END_SRC 

** DAP: Debugging support

#+BEGIN_SRC emacs-lisp

;; (use-package dap-mode
;;   :config
;;   (dap-auto-configure-mode))

#+END_SRC 

** Realgud

#+BEGIN_SRC emacs-lisp

(use-package realgud)

#+END_SRC 

** Tree-Sitter

#+BEGIN_SRC emacs-lisp

(use-package tree-sitter
  :config
  (global-tree-sitter-mode)
  :hook
  (tree-sitter-mode . tree-sitter-hl-mode))

(use-package tree-sitter-langs)

#+END_SRC

** Wakatime
Wakatime makes it easy for me to keep track of how much time I'm spending on various projects.

#+BEGIN_SRC emacs-lisp

(use-package wakatime-mode
  :config
  (global-wakatime-mode))

#+END_SRC


** C/C++

#+begin_src emacs-lisp

;; (add-hook 'c-mode-hook 'lsp)
;; (add-hook 'c++-mode-hook 'lsp)
(add-hook 'c-mode-hook 'eglot-ensure)
(add-hook 'c++-mode-hook 'eglot-ensure)

#+end_src

** Clojure

#+BEGIN_SRC emacs-lisp

(use-package clojure-mode
  :mode "\\.clj\\'"
  :hook ((clojure-mode . eglot-ensure)
         (clojurescript-mode . eglot-ensure)
         (clojurec-mode . eglot-ensure)))

(use-package cider)

#+END_SRC 

** GLSL: OpenGL shaders

#+BEGIN_SRC emacs-lisp

(use-package glsl-mode
  :mode ("\\.glsl\\'" "\\.vert\\'" "\\.frag\\'" "\\.geom\\'"))

#+END_SRC

The company backend needs the ~glslang~ package installed for ~glslangValidator~.

#+BEGIN_SRC emacs-lisp

;; (use-package company-glsl
;;   :after glsl-mode
;;   :config (add-to-list 'company-backends 'company-glsl))

#+END_SRC 

** Go
#+BEGIN_SRC emacs-lisp

(use-package go-mode
  :mode "\\.go\\'"
  :hook (go-mode . eglot-ensure))

#+END_SRC 

** Java

#+BEGIN_SRC emacs-lisp

;; (use-package meghanada
;;   :hook
;;   (java-mode . meghanada-mode)
;;   (java-mode . flycheck-mode))

;; (setq meghanada-java-path "java"
;;       meghanada-maven-path "mvn")

;; (use-package lsp-java
;;   :hook
;;   (java-mode . lsp))
  

#+END_SRC

** Python

#+BEGIN_SRC emacs-lisp

;; (use-package lsp-pyright)

(use-package python-mode
  :hook (python-mode . (lambda ()
                         (eglot-ensure)
                         (setq tab-width 4)))
  :custom
  (python-shell-interpreter "python3"))
  ;;(dap-python-debugger 'debugpy))

;; (require 'lsp-pyright)
;; (require 'dap-python)


#+END_SRC

** Typescript

#+begin_src emacs-lisp :results output

(use-package typescript-mode
  :mode "\\.ts\\'"
  ;; :hook (typescript-mode . lsp-deferred)
  :config
  (setq typescript-indent-level 4))

#+end_src

#+RESULTS:

** Retro Assembly
My configurations for various retro assembly architectures.

*** 6502
Programming for the C64 and NES.

#+BEGIN_SRC emacs-lisp

(use-package ca65-mode
  :mode "\\.s\\'")

#+END_SRC

** Rust
Inspired by https://robert.kra.hn/posts/2021-02-07_rust-with-emacs/

Most Rustic keybindings begin with =C-c C-c=

#+begin_src emacs-lisp

(use-package rustic
  :hook (rustic-mode . eglot-ensure)
  :custom
  (rustic-lsp-client 'eglot))
  ;; :bind (:map rustic-mode-map
              ;; ("M-j" . lsp-ui-imenu)
              ;; ("M-?" . lsp-find-references)))
  ;; :config
  ;; uncomment for less flashiness
  ;; (setq lsp-eldoc-hook nil)
  ;; (setq lsp-enable-symbol-highlighting nil)
  ;; (setq lsp-signature-auto-activate nil)

  ;; comment to disable rustfmt on save
  ;; (setq rustic-format-on-save t))


#+end_src

#+RESULTS:

** Web
Editing in a mixed-language web format.

#+BEGIN_SRC emacs-lisp

(use-package web-mode
    :commands (web-mode)
    :mode (("\\.html" . web-mode)
            ("\\.htm" . web-mode)
;           ("\\.tsx$" . web-mode)
            ("\\.mustache\\'" . web-mode)
            ("\\.phtml\\'" . web-mode)
            ("\\.as[cp]x\\'" . web-mode)
            ("\\.erb\\'" . web-mode)
            ("\\.sgml\\'" . web-mode)))

#+END_SRC 

* IRC
I use the ~erc-sasl~ implementation provided [[https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Bchat/erc/local/erc-sasl/erc-sasl.el][here]], so you'll have to download it before running this.

Set up SASL for [[libera.chat]].
#+BEGIN_SRC emacs-lisp

;; (require 'erc-sasl)

;; (add-to-list 'erc-sasl-server-regexp-list "irc\\.libera\\.chat")

;; ;; Redefine/Override the erc-login() function from the erc package, so that
;; ;; it now uses SASL
;; (defun erc-login ()
;;   "Perform user authentication at the IRC server. (PATCHED)"
;;   (erc-log (format "login: nick: %s, user: %s %s %s :%s"
;;            (erc-current-nick)
;;            (user-login-name)
;;            (or erc-system-name (system-name))
;;            erc-session-server
;;            erc-session-user-full-name))
;;   (if erc-session-password
;;       (erc-server-send (format "PASS %s" erc-session-password))
;;     (message "Logging in without password"))
;;   (when (and (featurep 'erc-sasl) (erc-sasl-use-sasl-p))
;;     (erc-server-send "CAP REQ :sasl"))
;;   (erc-server-send (format "NICK %s" (erc-current-nick)))
;;   (erc-server-send
;;    (format "USER %s %s %s :%s"
;;        ;; hacked - S.B.
;;        (if erc-anonymous-login erc-email-userid (user-login-name))
;;        "0" "*"
;;        erc-session-user-full-name))
;;   (erc-update-mode-line))

#+END_SRC

Set up my basic IRC user info.
#+BEGIN_SRC emacs-lisp

(setq erc-server "irc.libera.chat"
      erc-nick "abcd987"              ; change this
      erc-autojoin-channels-alist '((Libera.Chat
                                     "#systemcrafters"
                                     "#emacs"
                                     "#go-nuts"
                                     "##rust"))
      erc-track-shorten-start 8
      erc-kill-buffer-on-part t
      erc-auto-query 'bury)

#+END_SRC

* Documents
** PDFs

#+BEGIN_SRC emacs-lisp

(use-package tablist)

(use-package pdf-tools
  :config
  (pdf-loader-install))

#+END_SRC

Extends ~saveplace-mode~ with support for PDFs using ~pdf-tools~
#+BEGIN_SRC emacs-lisp

(use-package saveplace-pdf-view)

#+END_SRC 

** Ebooks

#+BEGIN_SRC emacs-lisp

(use-package nov
  :mode "\\.epub\\'")

#+END_SRC





























































































